# Generated by Django 4.2.7 on 2025-12-31 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='hot_score',
            field=models.FloatField(default=0),
        ),
    ]
